version: 2
updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 10
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    open-pull-requests-limit: 10
    directory: /
    schedule:
      interval: weekly